version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - mbrobbel
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  rebase-strategy: disabled
