[package]
name = "tydi"
version = "0.0.0"
description = "An open specification for complex data structures over hardware streams"
authors = ["Johan Peltenburg", "Jeroen van Straten", "Matthijs Brobbel"]
edition = "2018"

[[bin]]
name = "tydi"
required-features = ["cli"]

[features]
cli = ["structopt"]
data = []
default = ["parser", "generator"]
generator = []
parser = ["nom"]

[dependencies]
nom = { version = "5", optional = true }
structopt = { version = "0.3", optional = true, default-features = false }
