[package]
name = "tydi"
version = "0.0.0"
description = "An open specification for complex data structures over hardware streams"
authors = ["Johan Peltenburg", "Jeroen van Straten", "Matthijs Brobbel"]
edition = "2018"

[features]
default = []
parser = ["nom"]
generator = []

[dependencies]
indexmap = "1.3"
nom = { version = "5", optional = true }
