name: Book

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      run: |
        mkdir -p $HOME/mdbook
        curl -L https://github.com/rust-lang/mdBook/releases/download/v0.3.5/mdbook-v0.3.5-x86_64-apple-darwin.tar.gz | tar xz -C $HOME/mdbook
        echo "::add-path::${HOME}/mdbook/"
    - name: Build
      run: mdbook build
      working-directory: book
    - uses: actions/upload-artifact@v1
      with:
        name: book
        path: book/book

  deploy:
    name: Deploy
    runs-on: macos-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: book
    - uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: ./book
        commit-message: Deploy to GitHub Pages
