name: Release

on:
  push:
    tags:
    - '**'

jobs:
  github:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}

  crates:
    name: Crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1.0.1
      with:
        command: publish
        args: --token ${{ secrets.CRATES_IO_TOKEN }}
